CREATE TABLE files (
    -- ファイルID（連番）: プライマリキー、自動採番
    file_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- ユーザID: 外部キー (usersテーブルを参照)
    user_id BIGINT NOT NULL,
    -- ファイル名: NULL非許容
    file_name TEXT NOT NULL,
    -- ファイルの値: NULL許容 (内容によっては BYTEA 型も検討)
    file_value TEXT,
    -- 削除フラグ: デフォルトは false
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    -- 作成日: デフォルトは現在時刻
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- 更新日: デフォルトは現在時刻
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- 外部キー制約の定義
    CONSTRAINT fk_users
        FOREIGN KEY(user_id) 
        REFERENCES users(user_id)
        -- オプション: ユーザー削除時にファイルも削除する
        ON DELETE CASCADE
);

-- テーブルとカラムにコメントを設定
COMMENT ON TABLE files IS 'ファイル';
COMMENT ON COLUMN files.file_id IS 'ファイルID（連番）';
COMMENT ON COLUMN files.user_id IS 'ユーザID';
COMMENT ON COLUMN files.file_name IS 'ファイル名';
COMMENT ON COLUMN files.file_value IS 'ファイルの値';
COMMENT ON COLUMN files.deleted IS '削除フラグ';
COMMENT ON COLUMN files.created_at IS '作成日';
COMMENT ON COLUMN files.updated_at IS '更新日';