CREATE TABLE clips (
    -- クリップID（連番）: プライマリキー、自動採番
    clip_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- ユーザID: 外部キー (usersテーブルを参照)
    user_id BIGINT NOT NULL,
    -- クリップ名: NULL非許容
    clip_name TEXT NOT NULL,
    -- クリップの値: NULL許容 (内容によっては BYTEA 型も検討)
    clip_value TEXT,
    -- 削除フラグ: デフォルトは false
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    -- 作成日: デフォルトは現在時刻
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- 更新日: デフォルトは現在時刻
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- 外部キー制約の定義
    CONSTRAINT fk_users
        FOREIGN KEY(user_id) 
        REFERENCES users(user_id)
        -- オプション: ユーザー削除時にクリップも削除する
        ON DELETE CASCADE
);

-- テーブルとカラムにコメントを設定
COMMENT ON TABLE clips IS 'クリップ';
COMMENT ON COLUMN clips.clip_id IS 'クリップID（連番）';
COMMENT ON COLUMN clips.user_id IS 'ユーザID';
COMMENT ON COLUMN clips.clip_name IS 'クリップ名';
COMMENT ON COLUMN clips.clip_value IS 'クリップの値';
COMMENT ON COLUMN clips.deleted IS '削除フラグ';
COMMENT ON COLUMN clips.created_at IS '作成日';
COMMENT ON COLUMN clips.updated_at IS '更新日';