CREATE TABLE users (
    -- ユーザID（連番）: プライマリキー、自動採番
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- ユーザー名: NULL非許容
    user_name TEXT NOT NULL,
    -- パスワード: NULL非許容 (ハッシュ化して保存することを推奨)
    password TEXT NOT NULL,
    -- 削除フラグ: デフォルトは false
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    -- 作成日: デフォルトは現在時刻
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- 更新日: デフォルトは現在時刻
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- テーブルとカラムにコメントを設定
COMMENT ON TABLE users IS 'ユーザー';
COMMENT ON COLUMN users.user_id IS 'ユーザID（連番）';
COMMENT ON COLUMN users.user_name IS 'ユーザー名';
COMMENT ON COLUMN users.password IS 'パスワード';
COMMENT ON COLUMN users.deleted IS '削除フラグ';
COMMENT ON COLUMN users.created_at IS '作成日';
COMMENT ON COLUMN users.updated_at IS '更新日';